// Non-duplicate questions derived from Final Practice Q's.pptx.
window.finalPracticeUniqueQuestions = [
// Module 7
{m:7,q:'Which pair is released by the posterior pituitary but synthesized in hypothalamic neurons?',o:['ADH and oxytocin','Growth hormone and prolactin','ACTH and TSH','FSH and LH'],a:0,r:'ADH and oxytocin are synthesized in hypothalamic nuclei, transported down axons, and stored and released from the posterior pituitary.'},
{m:7,q:'Which combination represents the most common clinically functioning pituitary neuroendocrine tumour secretions?',o:['Growth hormone and prolactin','FSH and LH','ADH and oxytocin','Aldosterone and cortisol'],a:0,r:'Prolactin- and growth-hormone-secreting pituitary tumours are among the most common functioning pituitary adenomas; posterior hormones are not synthesized there.'},
{m:7,q:'A patient with acromegaly develops hyperglycemia. Which action of excess growth hormone contributes most?',o:['Insulin antagonism with increased hepatic glucose production and reduced peripheral uptake','Direct destruction of pancreatic beta cells','Increased renal glucose reabsorption only','Suppression of glucagon secretion'],a:0,r:'Growth hormone is counter-regulatory: excess GH promotes insulin resistance and hepatic glucose production, predisposing to hyperglycemia and diabetes.'},
{m:7,q:'Which finding would be least consistent with untreated acromegaly?',o:['Underactive sweat and sebaceous glands','Macroglossia','Coarse facial features and enlarged extremities','Hypertension and cardiomyopathy'],a:0,r:'Acromegaly commonly causes enlarged and overactive sweat/sebaceous glands, soft-tissue overgrowth, bony enlargement, and cardiovascular complications.'},
{m:7,q:'A patient has perioral numbness, carpopedal spasm, and a positive Trousseau sign after thyroid surgery. Which disorder is most likely?',o:['Hypoparathyroidism with hypocalcemia','Hyperparathyroidism with hypercalcemia','Graves disease with thyrotoxicosis','SIADH with hypernatremia'],a:0,r:'Low PTH after surgery reduces serum calcium, increasing neuromuscular excitability and producing tetany and Trousseau or Chvostek signs.'},
{m:7,q:'Which hormone lowers serum calcium and where is it produced?',o:['Calcitonin from thyroid parafollicular C cells','Calcitriol from parathyroid chief cells','PTH from thyroid follicular cells','Vitamin D from posterior pituitary cells'],a:0,r:'Thyroid C cells secrete calcitonin, which can inhibit osteoclast activity and favour renal calcium excretion.'},
{m:7,q:'A patient has very high urine output, thirst, high serum osmolality, and low urine specific gravity. Which condition best integrates the findings?',o:['Diabetes insipidus','SIADH','Primary hyperaldosteronism','Hyperparathyroidism'],a:0,r:'Inadequate ADH effect prevents urine concentration, causing free-water loss, dilute urine, thirst, and hyperosmolar plasma.'},
{m:7,q:'A patient with SIADH has concentrated urine despite hypo-osmolar plasma. Which renal structure is responding inappropriately to ADH?',o:['Collecting-duct principal cells inserting aquaporin-2','Proximal tubules inserting glucose transporters','Thick ascending limb secreting water','Glomerular podocytes filtering ADH'],a:0,r:'ADH activates V2 receptors on collecting-duct principal cells and inserts aquaporin-2, retaining water even when plasma is already dilute.'},
{m:7,q:'Which complication is most directly associated with hyperparathyroidism rather than hypoparathyroidism?',o:['Nephrolithiasis from hypercalcemia and hypercalciuria','Tetany from increased neuromuscular excitability','Positive Trousseau sign','Laryngospasm from low ionized calcium'],a:0,r:'PTH excess raises bone turnover and serum calcium, increasing filtered calcium and kidney-stone risk; tetany is characteristic of hypocalcemia.'},
{m:7,q:'Graves disease suppresses pituitary TSH even though thyroid activity is excessive. What drives the gland?',o:['Immunoglobulins activating the TSH receptor','Pituitary production of thyroid hormone','Antibodies destroying all thyroid follicles','Calcitonin binding the TSH receptor'],a:0,r:'Thyroid-stimulating immunoglobulins mimic TSH at its receptor. High T3/T4 then suppress endogenous TSH by negative feedback.'},

// Module 8
{m:8,q:'Which adrenergic receptor generalization best matches the seminar material?',o:['Alpha-1 and beta-1 receptors tend to mediate excitatory target effects, whereas alpha-2 and beta-2 often mediate inhibitory or relaxant effects','All alpha receptors are inhibitory and all beta receptors are excitatory','Only beta-3 receptors participate in stress','Adrenergic receptor subtype does not affect tissue response'],a:0,r:'Receptor effects vary by tissue, but the course framing contrasts many type-1 excitatory effects with type-2 inhibitory or smooth-muscle-relaxing effects.'},
{m:8,q:'Which statement about neurotransmission is most accurate?',o:['A neuron may contain more than one transmitter, and a postsynaptic cell can express several receptor types','Every neuron synthesizes exactly one transmitter','Each postsynaptic membrane has only one receptor species','A neurotransmitter has the same effect at every receptor'],a:0,r:'Neurons can co-release transmitters, postsynaptic membranes express multiple receptors, and a transmitter may have different effects depending on receptor subtype.'},
{m:8,q:'A membrane potential shifts from -70 mV to -80 mV while threshold remains -50 mV. What happens to excitability?',o:['It decreases because a larger depolarization is required to reach threshold','It increases because the membrane is closer to threshold','The action-potential amplitude doubles','Threshold becomes irrelevant'],a:0,r:'Hyperpolarization moves the resting potential farther from threshold, making an action potential less likely.'},
{m:8,q:'Which transmitter is not part of the classic monoamine hypothesis of depression?',o:['Glutamate','Serotonin','Norepinephrine','Dopamine'],a:0,r:'The classic monoamine hypothesis centres on serotonin, norepinephrine, and dopamine. Glutamate is important in newer circuit and plasticity models but is not a monoamine.'},
{m:8,q:'A patient experiences a manic episode with psychosis but has never had major depression. Which diagnosis is supported?',o:['Bipolar I disorder','Bipolar II disorder','Cyclothymia only','Major depressive disorder'],a:0,r:'A single manic episode establishes bipolar I disorder; a depressive episode is not required. Psychosis makes an elevated episode manic rather than hypomanic.'},
{m:8,q:'Why is glutamate implicated in schizophrenia even though the classic hypothesis emphasizes dopamine?',o:['NMDA-receptor hypofunction can disrupt cortical and interneuron circuits and secondarily alter dopamine pathways','Glutamate is found only outside the brain','NMDA activation eliminates all psychosis','Glutamate directly converts to dopamine in synaptic vesicles'],a:0,r:'Glutamatergic, especially NMDA, dysfunction may impair cortical integration and inhibitory interneurons, contributing to cognitive/negative symptoms and altered dopamine signaling.'},
{m:8,q:'Which pair is the most characteristic set of positive schizophrenia symptoms?',o:['Hallucinations and delusions','Avolition and flat affect','Poor working memory and impaired planning','Social withdrawal and anhedonia'],a:0,r:'Positive symptoms add abnormal experiences or beliefs, especially hallucinations and delusions. The other pairs are negative or cognitive symptoms.'},
{m:8,q:'Why does cation entry through AMPA receptors increase the probability of neuronal firing?',o:['Net sodium influx depolarizes the postsynaptic membrane toward threshold','Potassium influx makes the inside more negative','Calcium leaves the neuron and hyperpolarizes it','It reduces membrane conductance to zero'],a:0,r:'AMPA activation creates a net inward positive current at resting potential, generating an excitatory postsynaptic potential.'},
{m:8,q:'Which brain structure is the primary organ coordinating perception and integration of a stressor?',o:['Brain','Adrenal cortex','Heart','Kidney'],a:0,r:'The brain evaluates threat and coordinates autonomic, neuroendocrine, behavioural, and immune responses.'},
{m:8,q:'A patient has severe recurrent depression plus episodes of elevated energy lasting four days without marked impairment or psychosis. Which bipolar pattern is most likely?',o:['Bipolar II if the elevated periods meet hypomanic criteria','Bipolar I because any elevated mood is mania','Schizophrenia because sleep is reduced','Cyclothymia regardless of depressive severity'],a:0,r:'Bipolar II requires hypomania and major depression without a history of mania. Hypomania is shorter and lacks marked impairment or psychosis.'},

// Module 9
{m:9,q:'Which combination correctly describes major astrocyte functions?',o:['Extracellular ion regulation and neurotransmitter uptake/support','Myelin production in peripheral nerves and antibody secretion','CSF production and platelet formation','Phagocytosis as their only role'],a:0,r:'Astrocytes buffer ions, handle neurotransmitters, support metabolism and synapses, and contribute to BBB regulation. Microglia are the main CNS phagocytes.'},
{m:9,q:'CSF leaves the subarachnoid space and returns to venous blood primarily through:',o:['Arachnoid villi and granulations','Choroid plexus','Cerebral aqueduct','Central canal only'],a:0,r:'Arachnoid granulations project into dural venous sinuses and allow pressure-dependent CSF absorption.'},
{m:9,q:'Which examination finding is least characteristic of meningeal irritation?',o:['Pain only when looking upward with the eyes','Nuchal rigidity','Positive Kernig sign','Positive Brudzinski sign'],a:0,r:'Meningeal irritation produces headache, photophobia, neck stiffness, and Kernig/Brudzinski signs; isolated extraocular upward gaze pain is not a classic meningeal sign.'},
{m:9,q:'Which virus has the strongest epidemiologic association with multiple sclerosis in the course material?',o:['Epstein-Barr virus','Influenza A','Herpes simplex virus type 1','Varicella only'],a:0,r:'Most people with MS are EBV seropositive, and prior EBV infection is strongly associated with later MS risk, although infection alone is insufficient.'},
{m:9,q:'Which immune populations coordinate much of the myelin-directed injury in multiple sclerosis?',o:['Th1/Th17 CD4 T cells, B-lineage cells, macrophages/microglia, and CD8 T cells','Eosinophils alone','Platelets and megakaryocytes','Only neutrophils in CSF'],a:0,r:'MS lesions reflect coordinated adaptive and innate immune activity involving autoreactive T and B cells plus macrophage/microglial effector injury.'},
{m:9,q:'A patient has unilateral orbital pain, lacrimation, ptosis, and nasal congestion in circadian bouts. Which mechanism produces the autonomic signs?',o:['Activation of the trigeminal-autonomic reflex','Isolated optic-nerve demyelination','Suppression of parasympathetic outflow','Cortical spreading depression alone'],a:0,r:'Cluster headache activates trigeminal pain pathways and cranial parasympathetic autonomic output, producing tearing, congestion, and ptosis.'},
{m:9,q:'A patient experiences a visual aura that slowly spreads across the visual field before migraine pain. Which event best explains the aura?',o:['Cortical spreading depression beginning in occipital cortex','Permanent optic-nerve infarction','Acute bacterial invasion of the meninges','Diffuse axonal shearing'],a:0,r:'Cortical spreading depression is a propagating wave of neuronal/glial depolarization followed by suppressed activity, often beginning occipitally in visual aura.'},
{m:9,q:'Which cranial sensory pathway is central to migraine pain transmission?',o:['Trigeminal nerve and trigeminovascular system','Facial motor nerve only','Vagus nerve only','Optic nerve without meningeal input'],a:0,r:'Activation and sensitization of trigeminal afferents innervating cranial vessels and meninges are central to migraine pain.'},
{m:9,q:'What is the earliest cellular event in the secondary injury cascade after traumatic brain injury?',o:['Membrane depolarization with excitatory amino-acid release','Late scar formation','Myelin repair and axonal sprouting','Resolution of BBB permeability'],a:0,r:'Mechanical injury triggers ionic shifts, depolarization, and glutamate release, followed by calcium overload, oxidative stress, inflammation, and delayed axonal injury.'},
{m:9,q:'A dominant-hemisphere stroke produces aphasia plus contralateral face and arm weakness. Which artery is most likely occluded?',o:['Middle cerebral artery','Anterior cerebral artery','Posterior cerebral artery','Posterior inferior cerebellar artery'],a:0,r:'The MCA supplies dominant lateral frontal/parietal language areas and lateral motor cortex serving face and upper limb.'},

// Module 10
{m:10,q:'Where is trabecular bone concentrated in a typical long bone?',o:['Epiphyses','Diaphyseal cortical shell only','Medullary canal fluid','Periosteum only'],a:0,r:'Spongy trabecular bone is abundant at the epiphyses, where it distributes load across joint ends; the diaphysis is predominantly cortical.'},
{m:10,q:'A repetitive throwing injury produces a spiral humeral fracture after weeks of deep aching pain. Which prior process likely weakened the bone?',o:['A stress fracture from repetitive loading','An acute ligament sprain','A joint subluxation','Primary septic arthritis'],a:0,r:'Repetitive submaximal loading can create microdamage faster than remodeling repairs it, producing a stress lesion that can progress to complete fracture.'},
{m:10,q:'What is the most common immediate cause of an acquired joint dislocation?',o:['Trauma','Congenital dysplasia','Rheumatoid arthritis alone','Tendon degeneration without force'],a:0,r:'Trauma is the common cause of acute dislocation, forcing articular surfaces to lose contact and damaging capsule, ligaments, nerves, or vessels.'},
{m:10,q:'Which immune cell population initiates and organizes much of the rheumatoid synovial inflammatory response?',o:['Activated CD4 T helper cells, including Th1 and Th17 patterns','Mature erythrocytes','Osteocytes only','Megakaryocytes'],a:0,r:'Activated CD4 T cells help initiate cytokine networks, B-cell/autoantibody responses, macrophage activation, pannus formation, and osteoclast stimulation.'},
{m:10,q:'Which component does not belong to the standard pain-perception matrix described in the course?',o:['Nociceptive-cerebral system','Sensory-discriminative system','Affective-motivational system','Cognitive-evaluative system'],a:0,r:'Pain perception is commonly organized into sensory-discriminative, affective-motivational, and cognitive-evaluative dimensions; “nociceptive-cerebral” is not one of the three named systems.'},
{m:10,q:'A diabetic foot ulcer spreads directly into adjacent bone. What microbiologic pattern is most likely?',o:['Polymicrobial infection','Pure viral infection','Only group B streptococcus','Sterile inflammation in every case'],a:0,r:'Contiguous osteomyelitis from chronic ulcers is often polymicrobial, with gram-positive, gram-negative, and sometimes anaerobic organisms.'},
{m:10,q:'Which description defines a sequestrum in chronic osteomyelitis?',o:['A fragment of devitalized necrotic bone separated from viable bone','New reactive bone surrounding infection','A sinus tract draining to skin','A subperiosteal abscess only'],a:0,r:'A sequestrum is dead avascular bone that can harbour organisms; an involucrum is reactive new bone surrounding the infected segment.'},
{m:10,q:'Why does biofilm on an orthopedic implant promote chronic osteomyelitis?',o:['Organisms embedded in matrix show reduced antibiotic susceptibility and evade immune clearance','Biofilm increases bone perfusion','It converts bacteria into viruses','It prevents bacterial adherence to implants'],a:0,r:'A biofilm anchors organisms to foreign material and creates protected, metabolically altered communities that resist antimicrobials and host defences.'},
{m:10,q:'Which histologic feature would be least supportive of malignancy in a bone tumour?',o:['A small inconspicuous nucleolus with low mitotic activity','High nuclear-to-cytoplasmic ratio','Irregular nuclear borders and excess chromatin','Numerous atypical mitoses'],a:0,r:'Malignant cells tend to show nuclear enlargement, irregularity, hyperchromasia, prominent nucleoli, and increased atypical mitoses.'},
{m:10,q:'A malignant bone tumour is most likely to cause persistent night pain partly because it:',o:['Invades tissue, disrupts cortex and periosteum, and interferes with blood supply','Suppresses all osteoclast activity','Remains completely encapsulated','Cannot produce inflammatory mediators'],a:0,r:'Aggressive growth destroys and expands bone, elevates periosteum, compromises perfusion, and invades adjacent tissue, producing progressive pain.'},

// Module 11
{m:11,q:'A patient has persistent thrombocytosis from autonomous megakaryocyte proliferation without a reactive cause. Which diagnosis fits?',o:['Essential thrombocythemia','Immune thrombocytopenia','Thrombotic thrombocytopenic purpura','Heparin-induced thrombocytopenia'],a:0,r:'Essential thrombocythemia is a myeloproliferative neoplasm with sustained clonal megakaryocyte and platelet overproduction.'},
{m:11,q:'Which feature is least consistent with heparin-induced thrombocytopenia?',o:['IgA and IgM antibodies are the primary pathogenic antibodies','A hypercoagulable state','IgG against PF4-heparin complexes','Platelet activation and consumption'],a:0,r:'Clinically important HIT is driven mainly by IgG antibodies that activate platelets through Fc receptors, producing thrombocytopenia and thrombosis.'},
{m:11,q:'A strict vegan develops macrocytosis. Which erythroblast process is directly impaired by vitamin B12 deficiency?',o:['DNA synthesis and nuclear maturation','Hemoglobin oxygen binding','Membrane spectrin assembly only','Erythropoietin receptor signaling'],a:0,r:'B12 deficiency impairs thymidine/DNA synthesis, causing nuclear-cytoplasmic asynchrony, megaloblastosis, and ineffective erythropoiesis.'},
{m:11,q:'Which process does not cause hemolytic anemia?',o:['Immune destruction of bone-marrow progenitor cells','Antibody binding to red-cell antigens','Complement activation on red cells','Intrinsic abnormal red-cell shape or membrane'],a:0,r:'Destruction of marrow progenitors causes reduced production, as in aplastic anemia. Hemolysis is premature destruction of circulating red cells.'},
{m:11,q:'Which lymphoma is a highly aggressive B-cell non-Hodgkin lymphoma and an important childhood lymphoma?',o:['Burkitt lymphoma','Classical Hodgkin lymphoma','Follicular lymphoma only in older adults','Cutaneous T-cell lymphoma'],a:0,r:'Burkitt lymphoma is a rapidly proliferating mature B-cell lymphoma associated with MYC rearrangement and is prominent among childhood NHLs.'},
{m:11,q:'Why do acute leukemias commonly produce severe marrow crowding?',o:['Poorly differentiated blasts proliferate rapidly and fail to mature','Mature cells survive normally for decades','Only lymph nodes are involved','Erythropoietin directly fills the marrow with red cells'],a:0,r:'AML and ALL expand immature blasts rapidly in marrow, displacing normal hematopoiesis and causing anemia, infection, and bleeding.'},
{m:11,q:'An older adult is asymptomatic except for lymphocytosis and painless lymphadenopathy. Which leukemia is most likely?',o:['Chronic lymphocytic leukemia','Acute myeloid leukemia','Acute promyelocytic leukemia','Chronic myeloid leukemia in blast crisis'],a:0,r:'CLL is often incidentally discovered in older adults; when symptomatic, lymphadenopathy and recurrent infection are common.'},
{m:11,q:'What is the most common leukemia in adults overall?',o:['Chronic lymphocytic leukemia','Acute lymphoblastic leukemia','Hairy-cell leukemia','Acute promyelocytic leukemia'],a:0,r:'CLL is the most common adult leukemia in many Western populations, whereas ALL predominates in children.'},
{m:11,q:'A patient with leukemia has rod-like azurophilic inclusions in blasts. What do these structures represent?',o:['Aggregated primary granule material in myeloid blasts','Antibodies on malignant B cells','Nuclear fragments in reticulocytes','Platelet microtubules'],a:0,r:'Auer rods are needle-like cytoplasmic aggregates of azurophilic granules that support myeloid lineage, especially AML.'},
{m:11,q:'Which statement best distinguishes leukemia from an isolated reactive leukocytosis?',o:['Leukemia involves clonal uncontrolled proliferation with impaired normal marrow function','Any high white count is leukemia','Reactive leukocytosis always causes marrow replacement','Leukemia preserves all normal cell production'],a:0,r:'Leukemia is a clonal malignancy that crowds marrow and disrupts normal hematopoiesis; reactive leukocytosis is regulated and stimulus driven.'},

// Module 12
{m:12,q:'Which statement about a typical varicocele is false?',o:['It occurs more often on the right than the left','It is often painless','It consists of dilated tortuous testicular veins','It is associated with impaired fertility'],a:0,r:'Varicoceles are much more common on the left because of venous anatomy. They may raise scrotal temperature and impair sperm production.'},
{m:12,q:'A painless scrotal swelling develops after inguinal hernia repair and transilluminates. Which condition is most likely?',o:['Hydrocele','Testicular torsion','Acute epididymitis','Incarcerated hernia'],a:0,r:'A hydrocele is fluid within the tunica vaginalis and may follow disruption of lymphatic drainage or surgery; it is typically painless and transilluminates.'},
{m:12,q:'Which childhood condition increases later testicular cancer risk even after surgical correction?',o:['Cryptorchidism','Simple hydrocele','Spermatocele','Torsion of appendix testis'],a:0,r:'An undescended testis is associated with impaired fertility and elevated germ-cell tumour risk; orchiopexy improves surveillance but does not eliminate risk.'},
{m:12,q:'An adolescent with mumps develops severe testicular pain and swelling. Which complication has occurred?',o:['Orchitis','Hydrocele','Varicocele','Testicular torsion'],a:0,r:'Postpubertal mumps can cause orchitis, which may injure seminiferous tissue and occasionally impair fertility.'},
{m:12,q:'Enterobacteriaceae such as E. coli commonly cause which prostate disorders?',o:['Both acute and chronic bacterial prostatitis','Prostate cancer only','Benign prostatic hyperplasia only','Nonbacterial pelvic pain exclusively'],a:0,r:'Ascending or refluxed urinary gram-negative organisms commonly cause acute bacterial prostatitis and can persist in chronic bacterial prostatitis.'},
{m:12,q:'Most prostate adenocarcinomas arise from which cell compartment?',o:['Luminal or basal epithelial lineage, most often gland-forming luminal cells','Fibroblasts only','Resident lymphocytes','Leydig cells'],a:0,r:'Prostate adenocarcinoma is an epithelial malignancy, usually showing luminal secretory differentiation rather than stromal or immune origin.'},
{m:12,q:'Which ovarian hormone primarily drives proliferative endometrial growth before ovulation?',o:['Estradiol','Progesterone','LH','Inhibin alone'],a:0,r:'Follicular estradiol stimulates the proliferative phase. After ovulation, corpus-luteum progesterone converts the endometrium to a secretory state.'},
{m:12,q:'Which structure is the main source of progesterone during the luteal phase before placental takeover?',o:['Corpus luteum','Corpus albicans','Primary follicle','Anterior pituitary'],a:0,r:'After ovulation, the ruptured dominant follicle becomes the corpus luteum and secretes progesterone to support secretory endometrium.'},
{m:12,q:'What is the most common cause of secondary dysmenorrhea?',o:['Endometriosis','Primary prostaglandin excess without pelvic disease','Polycystic ovary syndrome','Physiologic ovulation'],a:0,r:'Endometriosis is a leading and commonly cited most common cause of secondary dysmenorrhea, especially with dyspareunia or infertility.'},
{m:12,q:'True or false: polycystic ovarian morphology must be present on ultrasound to diagnose PCOS.',o:['False; diagnosis can be made using other Rotterdam criteria after exclusions','True; ultrasound is mandatory in every patient','True; biochemical hyperandrogenism is irrelevant','False; PCOS requires only insulin resistance'],a:0,r:'Under Rotterdam criteria, two of three features are sufficient: oligo/anovulation, clinical/biochemical hyperandrogenism, or polycystic ovarian morphology, after excluding mimics.'}
].map(x=>({module:'Module '+x.m,q:x.q,o:x.o,a:x.a,r:x.r,source:"Final Practice Q's.pptx; non-duplicate course concepts with expanded explanations",sourceGroup:'finalpracticeunique'}));
