// Imported from Module_Review_Questions_1-15.docx, with added answer explanations.
window.importedModule12Quiz = [
  {q:'Polycystic ovarian syndrome is the most common cause of ____________ in women.',o:['Dysmenorrhea','Infertility','Leiomyomas','Ovarian cancer'],a:1,r:'PCOS is a leading and commonly cited most common cause of anovulatory infertility. Follicular arrest produces chronic oligo-ovulation or anovulation, so ovulation does not occur reliably.'},
  {q:'Which of the following sexually transmitted infections can cause cervicitis?',o:['Chlamydia','Herpes simplex virus','Gonorrhea','All are correct'],a:3,r:'Chlamydia trachomatis and Neisseria gonorrhoeae are common causes of cervicitis, and herpes simplex virus can also inflame the cervix. Therefore all listed infections can cause cervicitis.'},
  {q:'Pain in the abdomen or pelvis occurring with dysmenorrhea, dyschezia, dyspareunia, vaginal bleeding, infertility, adhesions, and scarring anywhere in the abdomen and pelvis is generally caused by a condition called:',o:['Endometriosis','Leiomyomas','Endometrial polyps','Adenomyosis'],a:0,r:'Endometriosis is ectopic endometrial-like tissue that responds to cyclic hormones. Repeated bleeding and inflammation cause pain, fibrosis, adhesions, and impaired fertility.'},
  {q:'During the latent period of a herpes simplex virus infection, the genome of the virus is:',o:['Maintained in the host cell mitochondria','Maintained in the host macrophage lysosomes','Maintained in the host cell nucleus','Totally degraded'],a:2,r:'HSV establishes latency in sensory neurons as an episomal viral genome within the nucleus. Reactivation allows viral replication and transport back to peripheral tissue.'},
  {q:'Which of the following is the most likely pathophysiological mechanism involved in the development of prostate cancer?',o:['Decreased production of insulin-like growth factor in the prostate stroma','Alterations in the ratio of estrogen to dihydrotestosterone (DHT) within the prostate','Decreased estrogen production by prostate epithelial cells','Latent viral infection of prostate epithelial cells'],a:1,r:'Prostate growth and carcinogenesis are hormone responsive. Age-related changes in local androgen-estrogen balance and DHT signaling can promote abnormal epithelial growth; the other choices are not the characteristic mechanism in the course bank.'},
  {q:'Primary amenorrhea can be caused by which of the following alterations?',o:['Hypothalamic disorders that decrease gonadotropin-releasing hormone secretion','Anterior pituitary disorders that decrease follicle-stimulating hormone and luteinizing hormone release','An absence of ova within the ovaries','All are correct'],a:3,r:'Normal menstruation requires an intact hypothalamic-pituitary-ovarian axis and responsive reproductive tract. Failure at the hypothalamus, pituitary, or ovary can prevent menarche.'},
  {q:'Which of the following statements regarding dysfunctional uterine bleeding is incorrect?',o:['Dysfunctional uterine bleeding often occurs during anovulatory cycles','Dysfunctional uterine bleeding can cause iron-deficiency anemia if severe','Dysfunctional uterine bleeding is associated with a decreased estrogen-to-progesterone ratio','Dysfunctional uterine bleeding can occur in patients with polycystic ovary syndrome'],a:2,r:'Anovulation prevents formation of a normal corpus luteum, so progesterone is deficient relative to ongoing estrogenic stimulation. The problem is unopposed estrogen, not a decreased estrogen-to-progesterone ratio.'},
  {q:'Syphilis is a complex systemic sexually transmitted infection caused by:',o:['A helminth','A virus','A fungus','A spirochete'],a:3,r:'Syphilis is caused by Treponema pallidum, a spirochete capable of disseminating systemically and producing staged clinical disease.'},
  {q:'Which of the following is true regarding uterine leiomyomas?',o:['The majority of uterine leiomyomas remain small and asymptomatic','Uterine leiomyomas are tumors of the endometrium','Uterine leiomyomas can develop prior to menarche','Uterine leiomyomas generally increase in size at the fastest rate after menopause'],a:0,r:'Leiomyomas are benign smooth-muscle tumors of the myometrium. Many remain small and asymptomatic; they are hormone responsive, uncommon before menarche, and commonly regress after menopause.'},
  {q:'Symptoms of prostate cancer are similar to those of:',o:['Urinary tract infection','Epididymitis','Benign prostatic hyperplasia','Prostatitis'],a:2,r:'Both prostate cancer and BPH can produce lower urinary tract obstruction, including hesitancy, weak stream, incomplete emptying, and nocturia. Early peripheral-zone cancer may still be asymptomatic.'},
  {q:'Primary dysmenorrhea is caused by the release of which chemical mediator?',o:['Leukotrienes','Bradykinin','Prostaglandins','Histamine'],a:2,r:'Endometrial prostaglandin release near menstruation increases uterine smooth-muscle contraction, ischemia, and pain. Excess prostaglandin activity is central to primary dysmenorrhea.'},
  {q:'Which virus is considered a precursor for developing cervical intraepithelial neoplasia (CIN) and cervical cancer?',o:['Human papillomavirus (HPV)','Epstein-Barr virus (EBV)','Herpes simplex virus (HSV)','Cytomegalovirus (CMV)'],a:0,r:'Persistent infection with high-risk HPV, especially oncogenic types such as 16 and 18, drives CIN through viral proteins that disrupt p53 and Rb tumor-suppressor control.'},
  {q:'What is usually the first clinical manifestation of breast cancer?',o:['Nipple dimpling','Nipple discharge','Enlargement of one breast','Painless lump'],a:3,r:'A new painless breast mass is a common initial manifestation. Skin or nipple changes and discharge can occur, but they are less typical as the first finding.'},
  {q:'The most common cause of secondary amenorrhea is:',o:['Polycystic ovary syndrome','Hypothyroidism','Pregnancy','Endometriosis'],a:2,r:'Pregnancy must be excluded first in a person with secondary amenorrhea because it is the most common cause. Endocrine and structural causes are evaluated after pregnancy testing.'},
  {q:'Which of the following conditions is not associated with polycystic ovary syndrome?',o:['Anovulation','Diabetes insipidus','Dysfunctional uterine bleeding','Hyperandrogenism'],a:1,r:'PCOS is associated with hyperandrogenism, chronic anovulation, insulin resistance, and irregular or abnormal uterine bleeding. Diabetes insipidus is an ADH-related water-balance disorder and is not a feature of PCOS.'}
].map(x=>({module:'Module 12',...x,source:'Module_Review_Questions_1-15.docx; explanations checked against Module 12 learning material',sourceGroup:'module12quiz'}));
