// Original challenge questions derived from final exam prep seminar slides and notes.
window.seminarFinalQuestions = [
{m:7,q:'A patient with years of hyperglycemia develops retinopathy and nephropathy. Which mechanism most directly links persistent glucose exposure to inflammatory vascular injury?',o:['Advanced glycation end-products bind RAGE and amplify oxidative and inflammatory signaling','Insulin permanently blocks endothelial glucose entry','Glucagon converts collagen into ketones','Aquaporin-2 channels glycate circulating platelets'],a:0,r:'Nonenzymatic glycation produces AGEs that cross-link proteins and activate RAGE, promoting oxidative stress, inflammation, endothelial dysfunction, and microvascular damage.'},
{m:7,q:'In tissues that do not require insulin for glucose uptake, excess intracellular glucose is diverted through the polyol pathway. Why can this injure cells?',o:['Sorbitol accumulation and NADPH consumption create osmotic and oxidative stress','Sorbitol directly increases ATP without limit','The pathway removes all intracellular water','NADPH accumulation prevents glutathione function'],a:0,r:'Aldose reductase converts glucose to sorbitol while consuming NADPH. Sorbitol can accumulate osmotically and reduced NADPH availability weakens antioxidant defence.'},
{m:7,q:'A patient has enlarged hands, prognathism, sweating, arthralgia, and carpal tunnel symptoms. Which mediator produces much of the tissue overgrowth?',o:['Hepatic IGF-1 stimulated by excess growth hormone','Posterior pituitary ADH','Low ACTH with low cortisol','Calcitonin released by osteoclasts'],a:0,r:'In acromegaly, excess GH drives hepatic and local IGF-1, causing soft-tissue, cartilage, periosteal, and organ growth and contributing to nerve entrapment.'},
{m:7,q:'Why can severe anterior pituitary failure cause hypoglycemia after loss of ACTH?',o:['Cortisol deficiency reduces gluconeogenesis and glycogen reserves while increasing insulin sensitivity','Aldosterone directly converts glucose to potassium','TSH loss causes pancreatic beta-cell destruction','FSH deficiency prevents intestinal glucose absorption'],a:0,r:'ACTH deficiency lowers cortisol. Without cortisol support, hepatic glucose production and glycogen availability fall and insulin sensitivity rises.'},
{m:7,q:'A patient with autoimmune thyroiditis has antithyroid antibodies plus cytotoxic T-cell infiltration. Which hypersensitivity mechanisms are represented?',o:['Antibody-mediated and T-cell-mediated injury','Immediate IgE-mediated injury only','Immune-complex disease only','No adaptive immune mechanism'],a:0,r:'Hashimoto thyroiditis includes antibody-associated injury and direct T-cell/macrophage-mediated gland destruction, reflecting type II and type IV features.'},
{m:7,q:'PTH raises serum calcium while often lowering serum phosphate. Which paired renal actions best explain this divergence?',o:['Increased distal calcium reabsorption and decreased proximal phosphate reabsorption','Decreased calcium and phosphate filtration','Increased proximal phosphate reabsorption with calcium secretion','Aquaporin insertion with bicarbonate loss'],a:0,r:'PTH conserves calcium distally but causes phosphaturia by reducing proximal sodium-phosphate cotransport; it also promotes renal calcitriol activation.'},

{m:8,q:'Glutamate binds both AMPA and NMDA receptors at a resting postsynaptic membrane. Why does substantial NMDA current usually wait until AMPA channels open?',o:['AMPA-mediated depolarization expels the voltage-dependent magnesium block from NMDA channels','AMPA synthesizes glutamate inside the NMDA pore','NMDA receptors cannot bind glutamate at rest','Potassium entering through AMPA chemically removes magnesium'],a:0,r:'NMDA receptors require ligand binding and postsynaptic depolarization. AMPA sodium influx depolarizes the membrane and relieves magnesium blockade, permitting calcium and other ion flow.'},
{m:8,q:'A toxin prevents voltage-gated calcium channels from opening in the presynaptic terminal. Which step fails first?',o:['Synaptic vesicle fusion and neurotransmitter exocytosis','Postsynaptic receptor synthesis','Axonal resting membrane potential formation','Neurotransmitter reuptake from the cleft'],a:0,r:'An arriving action potential normally opens presynaptic calcium channels. Calcium triggers the vesicle-fusion machinery, so transmitter release falls when influx is blocked.'},
{m:8,q:'A drug increases chloride conductance through GABA-A receptors. Why can this inhibit firing even if the membrane voltage changes only slightly?',o:['Shunting conductance dissipates excitatory current and makes threshold harder to reach','Chloride activates NMDA calcium influx','GABA-A closes every potassium channel','The action potential becomes smaller once initiated'],a:0,r:'Opening chloride channels can hyperpolarize and also shunt incoming excitatory current, reducing the effect of excitatory postsynaptic potentials on threshold.'},
{m:8,q:'A patient has hallucinations, avolition, and impaired planning. Which pathway pattern best integrates all three findings?',o:['Mesolimbic dopamine excess plus mesocortical dopamine deficit','Uniform nigrostriatal dopamine excess','Isolated tuberoinfundibular dopamine loss','Normal dopamine with posterior pituitary failure'],a:0,r:'Mesolimbic hyperdopaminergia contributes to positive symptoms, whereas reduced mesocortical signaling contributes to negative and cognitive symptoms.'},
{m:8,q:'Damage to the hippocampal formation would most directly impair which function while sparing basic visual processing?',o:['Formation and consolidation of new episodic memories','Primary detection of light','Initiation of skeletal muscle contraction','Posterior pituitary hormone storage'],a:0,r:'The hippocampal formation is central to learning and consolidation of new episodic and spatial memory; primary vision depends on occipital cortex.'},
{m:8,q:'Repeated stress responses initially preserve adaptation but later increase cardiometabolic and affective disease risk. What converts allostasis into allostatic load?',o:['Repeated or dysregulated mediator activation creates cumulative physiologic wear','A single brief cortisol pulse permanently destroys the adrenal gland','Parasympathetic tone remains continuously dominant','The immune system stops interacting with the HPA axis'],a:0,r:'Allostatic load is the accumulated cost of repeated, prolonged, or poorly regulated stress-system activation across neuroendocrine, autonomic, metabolic, and immune systems.'},

{m:9,q:'Which statement correctly distinguishes the blood-brain barrier from the blood-CSF barrier?',o:['Brain capillary endothelial tight junctions form the BBB, whereas choroid plexus epithelial tight junctions form the blood-CSF barrier','Astrocytes alone form both physical barriers','Arachnoid villi form the BBB and neurons form the blood-CSF barrier','Both barriers are gaps between meningeal layers'],a:0,r:'The BBB resides at specialized cerebral endothelium supported by pericytes and astrocytes. The blood-CSF barrier is chiefly at choroid plexus epithelium.'},
{m:9,q:'During bacterial meningitis, organisms enter the leptomeninges and recruit large numbers of neutrophils. Where is this inflammatory exudate concentrated?',o:['Subarachnoid space and CSF','Epidural fat only','Inside astrocyte nuclei','Between skull cortex and periosteum only'],a:0,r:'Bacterial meningitis involves the pia-arachnoid and CSF within the subarachnoid space, where neutrophilic inflammation develops.'},
{m:9,q:'In ischemic penumbra, ATP depletion causes depolarization and glutamate release. Which downstream event most directly activates destructive proteases, phospholipases, and endonucleases?',o:['Sustained intracellular calcium accumulation','Extracellular potassium normalization','Rapid glycogen restoration','Reduced reactive oxygen species'],a:0,r:'Excitotoxic calcium overload activates enzymes that damage membranes, cytoskeleton, proteins, and DNA, pushing salvageable neurons toward death.'},
{m:9,q:'Why does inflammation expand secondary injury after an ischemic stroke?',o:['Activated glia and recruited leukocytes release cytokines and reactive oxygen species while barrier permeability and edema increase','Inflammation restores ATP before reperfusion','Cytokines permanently close all glutamate receptors','Leukocytes remove intracellular calcium without tissue injury'],a:0,r:'Danger signals from injured cells activate glia and circulating immunity. Their mediators injure neighbouring tissue and disrupt the BBB, worsening edema and penumbral damage.'},
{m:9,q:'Hyperphosphorylated tau contributes to Alzheimer disease primarily by causing which cellular failure?',o:['Microtubule destabilization disrupts axonal transport of organelles and nutrients','Extracellular myelin overproduction blocks synapses','Increased acetylcholine synthesis causes excitotoxicity','Tau binds hemoglobin and occludes capillaries'],a:0,r:'Abnormal tau detaches from microtubules and aggregates into tangles. Loss of microtubule stability impairs axonal transport, synaptic function, and neuronal survival.'},
{m:9,q:'After a frontal impact, a patient has a contusion in the occipital lobe. Which mechanism best explains this finding?',o:['A contrecoup injury from brain movement against the opposite inner skull','A coup injury directly beneath the frontal impact','Diffuse peripheral nerve demyelination','A spontaneous subarachnoid aneurysm unrelated to motion'],a:0,r:'In contrecoup injury, inertia causes the moving brain to strike the skull opposite the impact, producing focal parenchymal microhemorrhage there.'},

{m:10,q:'An osteoclast attaches tightly to bone and acidifies a sealed resorption compartment. What is the purpose of the acidic environment?',o:['It dissolves hydroxyapatite and permits proteases such as cathepsin K to degrade matrix','It stimulates osteoblasts to deposit osteoid inside the sealed zone','It converts collagen directly into calcium phosphate','It prevents lysosomal enzymes from functioning'],a:0,r:'Proton secretion dissolves mineral and creates conditions for proteolytic degradation of type I collagen and other matrix components.'},
{m:10,q:'A mutation severely reduces cathepsin K activity. Which osteoclast function is most directly impaired?',o:['Degradation of type I collagen in resorbed bone matrix','Attachment to osteopontin through integrins','Generation of osteoblasts from mesenchyme','Synthesis of hydroxyapatite crystals'],a:0,r:'Cathepsin K is a potent osteoclast protease specialized for degrading type I collagen in the acidic resorption lacuna.'},
{m:10,q:'Osteocytes detect reduced mechanical strain during prolonged bed rest. Which signaling response can contribute to bone loss?',o:['Increased sclerostin suppresses osteoblast Wnt signaling while resorption is relatively favoured','Osteocytes transform directly into chondrocytes','TRAP secretion builds new mineral','FGF23 increases intestinal phosphate absorption'],a:0,r:'Osteocytes translate mechanical load into remodeling signals. Unloading can increase sclerostin and reduce osteoblast activity, contributing to disuse bone loss.'},
{m:10,q:'Which osteocyte signal most directly promotes osteoclast differentiation?',o:['RANKL','Sclerostin binding to hemoglobin','FGF23 binding to collagen','Calcitonin released into the resorption lacuna'],a:0,r:'RANKL engages RANK on osteoclast precursors and is central to osteoclast formation and activation; OPG acts as a decoy receptor.'},
{m:10,q:'A patient has renal phosphate wasting and reduced calcitriol activity driven by excess osteocyte hormone. Which hormone is implicated?',o:['FGF23','Osteoprotegerin','Cathepsin K','Type I collagen'],a:0,r:'Osteocyte-derived FGF23 increases renal phosphate excretion and suppresses calcitriol production, lowering phosphate availability.'},
{m:10,q:'A destructive bone lesion is found in an adult. Why must metastatic disease be considered before a rare primary sarcoma?',o:['Metastases to bone are substantially more common than primary malignant bone tumours','All primary bone tumours occur only in children','Metastatic lesions cannot involve marrow','Primary sarcomas never cause pain'],a:0,r:'The skeleton is a common metastatic site, whereas primary malignant bone tumours are uncommon. Age, lesion pattern, and known primary cancers guide evaluation.'}
].map(x=>({module:'Module '+x.m,q:x.q,o:x.o,a:x.a,r:x.r,source:'Final exam prep Modules 7-10 seminar PowerPoint and speaker notes',sourceGroup:'seminarnew'}));
